before_install:
- sudo apt-get install texlive-binaries
install:
- export PATH="$HOME/miniconda/bin:$PATH"
- if ! command -v conda > /dev/null; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  -O miniconda.sh; bash miniconda.sh -b -p $HOME/miniconda -u; conda config --add
  channels conda-forge; conda config --set always_yes yes; conda update --all; conda
  install tectonic; fi
- conda info -a
cache:
  directories:
  - "$HOME/miniconda"
  - "$HOME/.cache/Tectonic"
script:
- cd ./src/
- tectonic ./schema.tex --print
- tectonic ./markov-chain.tex --print
- tectonic ./contour-plot.tex --print
- cd ../
deploy:
  provider: releases
  api_key:
    secure: Fm8nl7ohrT3BEx0CmQADPa0zp8jbDeEZ8d4vUeU4P7H6f2X5NWlXwfX1D/h36LTP3Y1B+2Lt5pfnnIGHmCk7ypUn5+YRILkSk1LaK0F7rvBXmj5bNcy5vZlQIFAeys/6cEor57yzXg8bqSbGUV/xN1G69MoJ2KF7MzOfJ6zpEFNQ8rMSn9xtOGK5o6E0DyIi4GU+7BWB+YXFT9T4ghRqkdchxMbcDL7lYvufnUc1D6R+GnvPZfM3v4n8YvlgbXN8siVFwYTyHLL56sZR47a+Xv8ocTm4baZCxYdoXcyUyy2VNMYmhwRP77e2Ifu0pwpTZzNh5Npq+wGz1GoTmqagNd4/jaMTmMaWBU6QWHuazs/tT9UC26h7BSUcWSS1f6tK4C1XBhaYQEaXwPslk3udGXo8f0WKdSTO0KfkXvgGLLVs4de2cFSbtgCNgp7kCknBF9KeXXViaRzOSVnJ4M0r5p257kXGmuFxPL87I555nAiLk8AuO1NLzo1WOvPzqkBmosSOQsbZ6xvzT88Nrm+y0hr4kUpQ/lUCGtZne8EsLe+RqxlN2EQMSipDASTGe0vrJI2wYfqhrDfuqyeYh06sGnlPrRgh91/xUAbaPqCKJBqZQL37GI1n7xwzRLGEImYM6dlOsc7wAxMXp2oPFCMg84hUHaVCGMmoV9KD8nBorko=
  file:
  - ./src/schema.pdf
  - ./src/markov-chain.pdf
  - ./src/contour-plot.pdf
  skip_cleanup: true
  on:
    tags: true
    branch: master
