before_install:
- sudo apt-get install texlive-binaries
install:
- export PATH="$HOME/miniconda/bin:$PATH"
# If not yet installed, obtain Miniconda
# and tectonic
# From tectonic docs
# https://tectonic-typesetting.github.io/en-US/install.html#the-anaconda-method
- if ! command -v conda > /dev/null; then
  wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  bash miniconda.sh -b -p $HOME/miniconda -u;
  conda config --add channels conda-forge;
  conda config --set always_yes yes;
  conda install tectonic==0.1.10;
  fi
# Install biber if required for compiling the references.
# Biber 2.5 is required for tectonic 0.1.8
- conda install -c malramsay biber==2.5 --yes
- conda info -a
# Workaround until tectonic 0.1.11 is available
- sudo mkdir -p ~/.config/Tectonic/
- echo "[[default_bundles]]" | sudo tee --append ~/.config/Tectonic/config.toml
- sudo echo "url = \"https://tectonic.newton.cx/bundles/tlextras-2018.1r0/bundle.tar\"" | sudo tee --append ~/.config/Tectonic/config.toml
cache:
  directories:
  - "$HOME/miniconda"
  - "$HOME/.cache/Tectonic"
script:
- cd ./src/
- tectonic ./schema.tex --print
- tectonic ./markov-chain.tex --print
- tectonic ./contour-plot.tex --print
- tectonic ./combinatorial.tex --print
- tectonic ./tree.tex --print
- tectonic ./unit-spheres.tex --print
- cd ../
deploy:
  provider: releases
  api_key:
    secure: Fm8nl7ohrT3BEx0CmQADPa0zp8jbDeEZ8d4vUeU4P7H6f2X5NWlXwfX1D/h36LTP3Y1B+2Lt5pfnnIGHmCk7ypUn5+YRILkSk1LaK0F7rvBXmj5bNcy5vZlQIFAeys/6cEor57yzXg8bqSbGUV/xN1G69MoJ2KF7MzOfJ6zpEFNQ8rMSn9xtOGK5o6E0DyIi4GU+7BWB+YXFT9T4ghRqkdchxMbcDL7lYvufnUc1D6R+GnvPZfM3v4n8YvlgbXN8siVFwYTyHLL56sZR47a+Xv8ocTm4baZCxYdoXcyUyy2VNMYmhwRP77e2Ifu0pwpTZzNh5Npq+wGz1GoTmqagNd4/jaMTmMaWBU6QWHuazs/tT9UC26h7BSUcWSS1f6tK4C1XBhaYQEaXwPslk3udGXo8f0WKdSTO0KfkXvgGLLVs4de2cFSbtgCNgp7kCknBF9KeXXViaRzOSVnJ4M0r5p257kXGmuFxPL87I555nAiLk8AuO1NLzo1WOvPzqkBmosSOQsbZ6xvzT88Nrm+y0hr4kUpQ/lUCGtZne8EsLe+RqxlN2EQMSipDASTGe0vrJI2wYfqhrDfuqyeYh06sGnlPrRgh91/xUAbaPqCKJBqZQL37GI1n7xwzRLGEImYM6dlOsc7wAxMXp2oPFCMg84hUHaVCGMmoV9KD8nBorko=
  file:
  - ./src/schema.pdf
  - ./src/markov-chain.pdf
  - ./src/contour-plot.pdf
  - ./src/combinatorial.pdf
  - ./src/tree.pdf
  - ./src/unit-spheres.pdf
  skip_cleanup: true
  on:
    tags: true
    branch: master
